sudo: required
language: generic
services:
    - docker
    
before_install:
    - docker build -t radoszem/react-test -f ./client/Dockerfile.dev ./client 
    
script:
    - docker run -e CI=true radoszem/react-test npm test

after_success:
    - docker build -t radoszem/multi-client ./client
    - docker build -t radoszem/multi-nginx ./nginx
    - docker build -t radoszem/multi-server ./server
    - docker build -t radoszem/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push radoszem/multi-client
    - docker push radoszem/multi-nginx
    - docker push radoszem/multi-server
    - docker push radoszem/multi-worker